/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSlugIndexRouteImport } from './routes/_authenticated/$slug/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin/events'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedSlugCommitteeRouteImport } from './routes/_authenticated/$slug/committee'
import { Route as AuthenticatedAdminEventsEventIdRouteImport } from './routes/_authenticated/admin/events_.$eventId'
import { Route as AuthenticatedAdminEventsNewRouteImport } from './routes/_authenticated/admin/events.new'
import { Route as AuthenticatedAdminApiKeysNewRouteImport } from './routes/_authenticated/admin/api-keys.new'
import { Route as AuthenticatedSlugOrgsOrgIdRouteImport } from './routes/_authenticated/$slug/orgs/$orgId'
import { Route as AuthenticatedSlugCommitteeTagsRouteImport } from './routes/_authenticated/$slug/committee/tags'
import { Route as AuthenticatedSlugCommitteeSubmissionsRouteImport } from './routes/_authenticated/$slug/committee/submissions'
import { Route as AuthenticatedSlugCommitteeSettingsRouteImport } from './routes/_authenticated/$slug/committee/settings'
import { Route as AuthenticatedSlugCommitteeProjectCategoriesRouteImport } from './routes/_authenticated/$slug/committee/project-categories'
import { Route as AuthenticatedSlugCommitteePlacesRouteImport } from './routes/_authenticated/$slug/committee/places'
import { Route as AuthenticatedSlugCommitteeOrganizationsRouteImport } from './routes/_authenticated/$slug/committee/organizations'
import { Route as AuthenticatedSlugCommitteeMembersRouteImport } from './routes/_authenticated/$slug/committee/members'
import { Route as AuthenticatedSlugCommitteeExportRouteImport } from './routes/_authenticated/$slug/committee/export'
import { Route as AuthenticatedSlugCommitteeDeadlinesRouteImport } from './routes/_authenticated/$slug/committee/deadlines'
import { Route as AuthenticatedAdminEventsEventIdIndexRouteImport } from './routes/_authenticated/admin/events_.$eventId.index'
import { Route as AuthenticatedSlugOrgsOrgIdIndexRouteImport } from './routes/_authenticated/$slug/orgs/$orgId.index'
import { Route as AuthenticatedAdminEventsEventIdUsersRouteImport } from './routes/_authenticated/admin/events_.$eventId.users'
import { Route as AuthenticatedSlugOrgsOrgIdMembersRouteImport } from './routes/_authenticated/$slug/orgs/$orgId.members'
import { Route as AuthenticatedSlugCommitteeTagsNewRouteImport } from './routes/_authenticated/$slug/committee/tags.new'
import { Route as AuthenticatedSlugCommitteeSubmissionsSubmissionIdRouteImport } from './routes/_authenticated/$slug/committee/submissions_/$submissionId'
import { Route as AuthenticatedSlugCommitteeProjectCategoriesNewRouteImport } from './routes/_authenticated/$slug/committee/project-categories.new'
import { Route as AuthenticatedSlugCommitteePlacesNewRouteImport } from './routes/_authenticated/$slug/committee/places.new'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId'
import { Route as AuthenticatedSlugCommitteeOrganizationsNewRouteImport } from './routes/_authenticated/$slug/committee/organizations.new'
import { Route as AuthenticatedSlugCommitteeDeadlinesNewRouteImport } from './routes/_authenticated/$slug/committee/deadlines.new'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.index'
import { Route as AuthenticatedSlugOrgsOrgIdMembersNewRouteImport } from './routes/_authenticated/$slug/orgs/$orgId.members.new'
import { Route as AuthenticatedSlugCommitteeTagsTagIdEditRouteImport } from './routes/_authenticated/$slug/committee/tags.$tagId.edit'
import { Route as AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRouteImport } from './routes/_authenticated/$slug/committee/project-categories.$categoryId.edit'
import { Route as AuthenticatedSlugCommitteePlacesPlaceIdEditRouteImport } from './routes/_authenticated/$slug/committee/places.$placeId.edit'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.projects'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.members'
import { Route as AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRouteImport } from './routes/_authenticated/$slug/committee/deadlines.$deadlineId.edit'
import { Route as AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRouteImport } from './routes/_authenticated/$slug/orgs/$orgId_/projects.$projectId.index'
import { Route as AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRouteImport } from './routes/_authenticated/$slug/orgs/$orgId_/projects.$projectId.submissions'
import { Route as AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRouteImport } from './routes/_authenticated/$slug/orgs/$orgId_/projects.$projectId.edit'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId_.projects.$projectId'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.projects.new'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.members.new'
import { Route as AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRouteImport } from './routes/_authenticated/$slug/orgs/$orgId_/projects.$projectId.submissions_.$submissionId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSlugIndexRoute = AuthenticatedSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSlugRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSlugCommitteeRoute =
  AuthenticatedSlugCommitteeRouteImport.update({
    id: '/committee',
    path: '/committee',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedAdminEventsEventIdRoute =
  AuthenticatedAdminEventsEventIdRouteImport.update({
    id: '/events_/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsNewRoute =
  AuthenticatedAdminEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminEventsRoute,
  } as any)
const AuthenticatedAdminApiKeysNewRoute =
  AuthenticatedAdminApiKeysNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminApiKeysRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdRoute =
  AuthenticatedSlugOrgsOrgIdRouteImport.update({
    id: '/orgs/$orgId',
    path: '/orgs/$orgId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCommitteeTagsRoute =
  AuthenticatedSlugCommitteeTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeSubmissionsRoute =
  AuthenticatedSlugCommitteeSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeSettingsRoute =
  AuthenticatedSlugCommitteeSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeProjectCategoriesRoute =
  AuthenticatedSlugCommitteeProjectCategoriesRouteImport.update({
    id: '/project-categories',
    path: '/project-categories',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteePlacesRoute =
  AuthenticatedSlugCommitteePlacesRouteImport.update({
    id: '/places',
    path: '/places',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsRoute =
  AuthenticatedSlugCommitteeOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeMembersRoute =
  AuthenticatedSlugCommitteeMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeExportRoute =
  AuthenticatedSlugCommitteeExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeDeadlinesRoute =
  AuthenticatedSlugCommitteeDeadlinesRouteImport.update({
    id: '/deadlines',
    path: '/deadlines',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedAdminEventsEventIdIndexRoute =
  AuthenticatedAdminEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEventsEventIdRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdIndexRoute =
  AuthenticatedSlugOrgsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugOrgsOrgIdRoute,
  } as any)
const AuthenticatedAdminEventsEventIdUsersRoute =
  AuthenticatedAdminEventsEventIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminEventsEventIdRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdMembersRoute =
  AuthenticatedSlugOrgsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSlugOrgsOrgIdRoute,
  } as any)
const AuthenticatedSlugCommitteeTagsNewRoute =
  AuthenticatedSlugCommitteeTagsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugCommitteeTagsRoute,
  } as any)
const AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute =
  AuthenticatedSlugCommitteeSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions_/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeProjectCategoriesNewRoute =
  AuthenticatedSlugCommitteeProjectCategoriesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugCommitteeProjectCategoriesRoute,
  } as any)
const AuthenticatedSlugCommitteePlacesNewRoute =
  AuthenticatedSlugCommitteePlacesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugCommitteePlacesRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdRouteImport.update({
    id: '/organizations_/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AuthenticatedSlugCommitteeRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsNewRoute =
  AuthenticatedSlugCommitteeOrganizationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugCommitteeOrganizationsRoute,
  } as any)
const AuthenticatedSlugCommitteeDeadlinesNewRoute =
  AuthenticatedSlugCommitteeDeadlinesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugCommitteeDeadlinesRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugCommitteeOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdMembersNewRoute =
  AuthenticatedSlugOrgsOrgIdMembersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugOrgsOrgIdMembersRoute,
  } as any)
const AuthenticatedSlugCommitteeTagsTagIdEditRoute =
  AuthenticatedSlugCommitteeTagsTagIdEditRouteImport.update({
    id: '/$tagId/edit',
    path: '/$tagId/edit',
    getParentRoute: () => AuthenticatedSlugCommitteeTagsRoute,
  } as any)
const AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute =
  AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRouteImport.update({
    id: '/$categoryId/edit',
    path: '/$categoryId/edit',
    getParentRoute: () => AuthenticatedSlugCommitteeProjectCategoriesRoute,
  } as any)
const AuthenticatedSlugCommitteePlacesPlaceIdEditRoute =
  AuthenticatedSlugCommitteePlacesPlaceIdEditRouteImport.update({
    id: '/$placeId/edit',
    path: '/$placeId/edit',
    getParentRoute: () => AuthenticatedSlugCommitteePlacesRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedSlugCommitteeOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedSlugCommitteeOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute =
  AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRouteImport.update({
    id: '/$deadlineId/edit',
    path: '/$deadlineId/edit',
    getParentRoute: () => AuthenticatedSlugCommitteeDeadlinesRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute =
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRouteImport.update({
    id: '/orgs/$orgId_/projects/$projectId/',
    path: '/orgs/$orgId/projects/$projectId/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute =
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRouteImport.update({
    id: '/orgs/$orgId_/projects/$projectId/submissions',
    path: '/orgs/$orgId/projects/$projectId/submissions',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute =
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRouteImport.update({
    id: '/orgs/$orgId_/projects/$projectId/edit',
    path: '/orgs/$orgId/projects/$projectId/edit',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRouteImport.update(
    {
      id: '/organizations_/$orgId_/projects/$projectId',
      path: '/organizations/$orgId/projects/$projectId',
      getParentRoute: () => AuthenticatedSlugCommitteeRoute,
    } as any,
  )
const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () =>
      AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () =>
      AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRoute,
  } as any)
const AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute =
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRouteImport.update(
    {
      id: '/orgs/$orgId_/projects/$projectId/submissions_/$submissionId',
      path: '/orgs/$orgId/projects/$projectId/submissions/$submissionId',
      getParentRoute: () => AuthenticatedSlugRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/$slug/committee': typeof AuthenticatedSlugCommitteeRouteWithChildren
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRouteWithChildren
  '/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/$slug/': typeof AuthenticatedSlugIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/$slug/committee/deadlines': typeof AuthenticatedSlugCommitteeDeadlinesRouteWithChildren
  '/$slug/committee/export': typeof AuthenticatedSlugCommitteeExportRoute
  '/$slug/committee/members': typeof AuthenticatedSlugCommitteeMembersRoute
  '/$slug/committee/organizations': typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  '/$slug/committee/places': typeof AuthenticatedSlugCommitteePlacesRouteWithChildren
  '/$slug/committee/project-categories': typeof AuthenticatedSlugCommitteeProjectCategoriesRouteWithChildren
  '/$slug/committee/settings': typeof AuthenticatedSlugCommitteeSettingsRoute
  '/$slug/committee/submissions': typeof AuthenticatedSlugCommitteeSubmissionsRoute
  '/$slug/committee/tags': typeof AuthenticatedSlugCommitteeTagsRouteWithChildren
  '/$slug/orgs/$orgId': typeof AuthenticatedSlugOrgsOrgIdRouteWithChildren
  '/admin/api-keys/new': typeof AuthenticatedAdminApiKeysNewRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/admin/events/$eventId': typeof AuthenticatedAdminEventsEventIdRouteWithChildren
  '/$slug/committee/deadlines/new': typeof AuthenticatedSlugCommitteeDeadlinesNewRoute
  '/$slug/committee/organizations/new': typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
  '/$slug/committee/organizations/$orgId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren
  '/$slug/committee/places/new': typeof AuthenticatedSlugCommitteePlacesNewRoute
  '/$slug/committee/project-categories/new': typeof AuthenticatedSlugCommitteeProjectCategoriesNewRoute
  '/$slug/committee/submissions/$submissionId': typeof AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute
  '/$slug/committee/tags/new': typeof AuthenticatedSlugCommitteeTagsNewRoute
  '/$slug/orgs/$orgId/members': typeof AuthenticatedSlugOrgsOrgIdMembersRouteWithChildren
  '/admin/events/$eventId/users': typeof AuthenticatedAdminEventsEventIdUsersRoute
  '/$slug/orgs/$orgId/': typeof AuthenticatedSlugOrgsOrgIdIndexRoute
  '/admin/events/$eventId/': typeof AuthenticatedAdminEventsEventIdIndexRoute
  '/$slug/committee/deadlines/$deadlineId/edit': typeof AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute
  '/$slug/committee/organizations/$orgId/members': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteWithChildren
  '/$slug/committee/organizations/$orgId/projects': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  '/$slug/committee/places/$placeId/edit': typeof AuthenticatedSlugCommitteePlacesPlaceIdEditRoute
  '/$slug/committee/project-categories/$categoryId/edit': typeof AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute
  '/$slug/committee/tags/$tagId/edit': typeof AuthenticatedSlugCommitteeTagsTagIdEditRoute
  '/$slug/orgs/$orgId/members/new': typeof AuthenticatedSlugOrgsOrgIdMembersNewRoute
  '/$slug/committee/organizations/$orgId/': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
  '/$slug/committee/organizations/$orgId/members/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute
  '/$slug/committee/organizations/$orgId/projects/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
  '/$slug/committee/organizations/$orgId/projects/$projectId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute
  '/$slug/orgs/$orgId/projects/$projectId/edit': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute
  '/$slug/orgs/$orgId/projects/$projectId/submissions': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute
  '/$slug/orgs/$orgId/projects/$projectId/': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute
  '/$slug/orgs/$orgId/projects/$projectId/submissions/$submissionId': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof PublicLoginRoute
  '/$slug/committee': typeof AuthenticatedSlugCommitteeRouteWithChildren
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRouteWithChildren
  '/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/$slug': typeof AuthenticatedSlugIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/$slug/committee/deadlines': typeof AuthenticatedSlugCommitteeDeadlinesRouteWithChildren
  '/$slug/committee/export': typeof AuthenticatedSlugCommitteeExportRoute
  '/$slug/committee/members': typeof AuthenticatedSlugCommitteeMembersRoute
  '/$slug/committee/organizations': typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  '/$slug/committee/places': typeof AuthenticatedSlugCommitteePlacesRouteWithChildren
  '/$slug/committee/project-categories': typeof AuthenticatedSlugCommitteeProjectCategoriesRouteWithChildren
  '/$slug/committee/settings': typeof AuthenticatedSlugCommitteeSettingsRoute
  '/$slug/committee/submissions': typeof AuthenticatedSlugCommitteeSubmissionsRoute
  '/$slug/committee/tags': typeof AuthenticatedSlugCommitteeTagsRouteWithChildren
  '/admin/api-keys/new': typeof AuthenticatedAdminApiKeysNewRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/$slug/committee/deadlines/new': typeof AuthenticatedSlugCommitteeDeadlinesNewRoute
  '/$slug/committee/organizations/new': typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
  '/$slug/committee/places/new': typeof AuthenticatedSlugCommitteePlacesNewRoute
  '/$slug/committee/project-categories/new': typeof AuthenticatedSlugCommitteeProjectCategoriesNewRoute
  '/$slug/committee/submissions/$submissionId': typeof AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute
  '/$slug/committee/tags/new': typeof AuthenticatedSlugCommitteeTagsNewRoute
  '/$slug/orgs/$orgId/members': typeof AuthenticatedSlugOrgsOrgIdMembersRouteWithChildren
  '/admin/events/$eventId/users': typeof AuthenticatedAdminEventsEventIdUsersRoute
  '/$slug/orgs/$orgId': typeof AuthenticatedSlugOrgsOrgIdIndexRoute
  '/admin/events/$eventId': typeof AuthenticatedAdminEventsEventIdIndexRoute
  '/$slug/committee/deadlines/$deadlineId/edit': typeof AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute
  '/$slug/committee/organizations/$orgId/members': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteWithChildren
  '/$slug/committee/organizations/$orgId/projects': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  '/$slug/committee/places/$placeId/edit': typeof AuthenticatedSlugCommitteePlacesPlaceIdEditRoute
  '/$slug/committee/project-categories/$categoryId/edit': typeof AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute
  '/$slug/committee/tags/$tagId/edit': typeof AuthenticatedSlugCommitteeTagsTagIdEditRoute
  '/$slug/orgs/$orgId/members/new': typeof AuthenticatedSlugOrgsOrgIdMembersNewRoute
  '/$slug/committee/organizations/$orgId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
  '/$slug/committee/organizations/$orgId/members/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute
  '/$slug/committee/organizations/$orgId/projects/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
  '/$slug/committee/organizations/$orgId/projects/$projectId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute
  '/$slug/orgs/$orgId/projects/$projectId/edit': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute
  '/$slug/orgs/$orgId/projects/$projectId/submissions': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute
  '/$slug/orgs/$orgId/projects/$projectId': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute
  '/$slug/orgs/$orgId/projects/$projectId/submissions/$submissionId': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$slug/committee': typeof AuthenticatedSlugCommitteeRouteWithChildren
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRouteWithChildren
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/$slug/': typeof AuthenticatedSlugIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/$slug/committee/deadlines': typeof AuthenticatedSlugCommitteeDeadlinesRouteWithChildren
  '/_authenticated/$slug/committee/export': typeof AuthenticatedSlugCommitteeExportRoute
  '/_authenticated/$slug/committee/members': typeof AuthenticatedSlugCommitteeMembersRoute
  '/_authenticated/$slug/committee/organizations': typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  '/_authenticated/$slug/committee/places': typeof AuthenticatedSlugCommitteePlacesRouteWithChildren
  '/_authenticated/$slug/committee/project-categories': typeof AuthenticatedSlugCommitteeProjectCategoriesRouteWithChildren
  '/_authenticated/$slug/committee/settings': typeof AuthenticatedSlugCommitteeSettingsRoute
  '/_authenticated/$slug/committee/submissions': typeof AuthenticatedSlugCommitteeSubmissionsRoute
  '/_authenticated/$slug/committee/tags': typeof AuthenticatedSlugCommitteeTagsRouteWithChildren
  '/_authenticated/$slug/orgs/$orgId': typeof AuthenticatedSlugOrgsOrgIdRouteWithChildren
  '/_authenticated/admin/api-keys/new': typeof AuthenticatedAdminApiKeysNewRoute
  '/_authenticated/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/_authenticated/admin/events_/$eventId': typeof AuthenticatedAdminEventsEventIdRouteWithChildren
  '/_authenticated/$slug/committee/deadlines/new': typeof AuthenticatedSlugCommitteeDeadlinesNewRoute
  '/_authenticated/$slug/committee/organizations/new': typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
  '/_authenticated/$slug/committee/organizations_/$orgId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren
  '/_authenticated/$slug/committee/places/new': typeof AuthenticatedSlugCommitteePlacesNewRoute
  '/_authenticated/$slug/committee/project-categories/new': typeof AuthenticatedSlugCommitteeProjectCategoriesNewRoute
  '/_authenticated/$slug/committee/submissions_/$submissionId': typeof AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute
  '/_authenticated/$slug/committee/tags/new': typeof AuthenticatedSlugCommitteeTagsNewRoute
  '/_authenticated/$slug/orgs/$orgId/members': typeof AuthenticatedSlugOrgsOrgIdMembersRouteWithChildren
  '/_authenticated/admin/events_/$eventId/users': typeof AuthenticatedAdminEventsEventIdUsersRoute
  '/_authenticated/$slug/orgs/$orgId/': typeof AuthenticatedSlugOrgsOrgIdIndexRoute
  '/_authenticated/admin/events_/$eventId/': typeof AuthenticatedAdminEventsEventIdIndexRoute
  '/_authenticated/$slug/committee/deadlines/$deadlineId/edit': typeof AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute
  '/_authenticated/$slug/committee/organizations_/$orgId/members': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteWithChildren
  '/_authenticated/$slug/committee/organizations_/$orgId/projects': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  '/_authenticated/$slug/committee/places/$placeId/edit': typeof AuthenticatedSlugCommitteePlacesPlaceIdEditRoute
  '/_authenticated/$slug/committee/project-categories/$categoryId/edit': typeof AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute
  '/_authenticated/$slug/committee/tags/$tagId/edit': typeof AuthenticatedSlugCommitteeTagsTagIdEditRoute
  '/_authenticated/$slug/orgs/$orgId/members/new': typeof AuthenticatedSlugOrgsOrgIdMembersNewRoute
  '/_authenticated/$slug/committee/organizations_/$orgId/': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
  '/_authenticated/$slug/committee/organizations_/$orgId/members/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute
  '/_authenticated/$slug/committee/organizations_/$orgId/projects/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
  '/_authenticated/$slug/committee/organizations_/$orgId_/projects/$projectId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute
  '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/edit': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute
  '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute
  '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute
  '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions_/$submissionId': typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/admin'
    | '/login'
    | '/$slug/committee'
    | '/admin/api-keys'
    | '/admin/events'
    | '/admin/users'
    | '/$slug/'
    | '/admin/'
    | '/$slug/committee/deadlines'
    | '/$slug/committee/export'
    | '/$slug/committee/members'
    | '/$slug/committee/organizations'
    | '/$slug/committee/places'
    | '/$slug/committee/project-categories'
    | '/$slug/committee/settings'
    | '/$slug/committee/submissions'
    | '/$slug/committee/tags'
    | '/$slug/orgs/$orgId'
    | '/admin/api-keys/new'
    | '/admin/events/new'
    | '/admin/events/$eventId'
    | '/$slug/committee/deadlines/new'
    | '/$slug/committee/organizations/new'
    | '/$slug/committee/organizations/$orgId'
    | '/$slug/committee/places/new'
    | '/$slug/committee/project-categories/new'
    | '/$slug/committee/submissions/$submissionId'
    | '/$slug/committee/tags/new'
    | '/$slug/orgs/$orgId/members'
    | '/admin/events/$eventId/users'
    | '/$slug/orgs/$orgId/'
    | '/admin/events/$eventId/'
    | '/$slug/committee/deadlines/$deadlineId/edit'
    | '/$slug/committee/organizations/$orgId/members'
    | '/$slug/committee/organizations/$orgId/projects'
    | '/$slug/committee/places/$placeId/edit'
    | '/$slug/committee/project-categories/$categoryId/edit'
    | '/$slug/committee/tags/$tagId/edit'
    | '/$slug/orgs/$orgId/members/new'
    | '/$slug/committee/organizations/$orgId/'
    | '/$slug/committee/organizations/$orgId/members/new'
    | '/$slug/committee/organizations/$orgId/projects/new'
    | '/$slug/committee/organizations/$orgId/projects/$projectId'
    | '/$slug/orgs/$orgId/projects/$projectId/edit'
    | '/$slug/orgs/$orgId/projects/$projectId/submissions'
    | '/$slug/orgs/$orgId/projects/$projectId/'
    | '/$slug/orgs/$orgId/projects/$projectId/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$slug/committee'
    | '/admin/api-keys'
    | '/admin/events'
    | '/admin/users'
    | '/$slug'
    | '/admin'
    | '/$slug/committee/deadlines'
    | '/$slug/committee/export'
    | '/$slug/committee/members'
    | '/$slug/committee/organizations'
    | '/$slug/committee/places'
    | '/$slug/committee/project-categories'
    | '/$slug/committee/settings'
    | '/$slug/committee/submissions'
    | '/$slug/committee/tags'
    | '/admin/api-keys/new'
    | '/admin/events/new'
    | '/$slug/committee/deadlines/new'
    | '/$slug/committee/organizations/new'
    | '/$slug/committee/places/new'
    | '/$slug/committee/project-categories/new'
    | '/$slug/committee/submissions/$submissionId'
    | '/$slug/committee/tags/new'
    | '/$slug/orgs/$orgId/members'
    | '/admin/events/$eventId/users'
    | '/$slug/orgs/$orgId'
    | '/admin/events/$eventId'
    | '/$slug/committee/deadlines/$deadlineId/edit'
    | '/$slug/committee/organizations/$orgId/members'
    | '/$slug/committee/organizations/$orgId/projects'
    | '/$slug/committee/places/$placeId/edit'
    | '/$slug/committee/project-categories/$categoryId/edit'
    | '/$slug/committee/tags/$tagId/edit'
    | '/$slug/orgs/$orgId/members/new'
    | '/$slug/committee/organizations/$orgId'
    | '/$slug/committee/organizations/$orgId/members/new'
    | '/$slug/committee/organizations/$orgId/projects/new'
    | '/$slug/committee/organizations/$orgId/projects/$projectId'
    | '/$slug/orgs/$orgId/projects/$projectId/edit'
    | '/$slug/orgs/$orgId/projects/$projectId/submissions'
    | '/$slug/orgs/$orgId/projects/$projectId'
    | '/$slug/orgs/$orgId/projects/$projectId/submissions/$submissionId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/$slug'
    | '/_authenticated/admin'
    | '/_public/login'
    | '/_authenticated/'
    | '/_authenticated/$slug/committee'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/users'
    | '/_authenticated/$slug/'
    | '/_authenticated/admin/'
    | '/_authenticated/$slug/committee/deadlines'
    | '/_authenticated/$slug/committee/export'
    | '/_authenticated/$slug/committee/members'
    | '/_authenticated/$slug/committee/organizations'
    | '/_authenticated/$slug/committee/places'
    | '/_authenticated/$slug/committee/project-categories'
    | '/_authenticated/$slug/committee/settings'
    | '/_authenticated/$slug/committee/submissions'
    | '/_authenticated/$slug/committee/tags'
    | '/_authenticated/$slug/orgs/$orgId'
    | '/_authenticated/admin/api-keys/new'
    | '/_authenticated/admin/events/new'
    | '/_authenticated/admin/events_/$eventId'
    | '/_authenticated/$slug/committee/deadlines/new'
    | '/_authenticated/$slug/committee/organizations/new'
    | '/_authenticated/$slug/committee/organizations_/$orgId'
    | '/_authenticated/$slug/committee/places/new'
    | '/_authenticated/$slug/committee/project-categories/new'
    | '/_authenticated/$slug/committee/submissions_/$submissionId'
    | '/_authenticated/$slug/committee/tags/new'
    | '/_authenticated/$slug/orgs/$orgId/members'
    | '/_authenticated/admin/events_/$eventId/users'
    | '/_authenticated/$slug/orgs/$orgId/'
    | '/_authenticated/admin/events_/$eventId/'
    | '/_authenticated/$slug/committee/deadlines/$deadlineId/edit'
    | '/_authenticated/$slug/committee/organizations_/$orgId/members'
    | '/_authenticated/$slug/committee/organizations_/$orgId/projects'
    | '/_authenticated/$slug/committee/places/$placeId/edit'
    | '/_authenticated/$slug/committee/project-categories/$categoryId/edit'
    | '/_authenticated/$slug/committee/tags/$tagId/edit'
    | '/_authenticated/$slug/orgs/$orgId/members/new'
    | '/_authenticated/$slug/committee/organizations_/$orgId/'
    | '/_authenticated/$slug/committee/organizations_/$orgId/members/new'
    | '/_authenticated/$slug/committee/organizations_/$orgId/projects/new'
    | '/_authenticated/$slug/committee/organizations_/$orgId_/projects/$projectId'
    | '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/edit'
    | '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions'
    | '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/'
    | '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions_/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/$slug/': {
      id: '/_authenticated/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof AuthenticatedSlugIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/$slug/committee': {
      id: '/_authenticated/$slug/committee'
      path: '/committee'
      fullPath: '/$slug/committee'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/admin/events_/$eventId': {
      id: '/_authenticated/admin/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AuthenticatedAdminEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events/new': {
      id: '/_authenticated/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AuthenticatedAdminEventsNewRouteImport
      parentRoute: typeof AuthenticatedAdminEventsRoute
    }
    '/_authenticated/admin/api-keys/new': {
      id: '/_authenticated/admin/api-keys/new'
      path: '/new'
      fullPath: '/admin/api-keys/new'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysNewRouteImport
      parentRoute: typeof AuthenticatedAdminApiKeysRoute
    }
    '/_authenticated/$slug/orgs/$orgId': {
      id: '/_authenticated/$slug/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/$slug/orgs/$orgId'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/committee/tags': {
      id: '/_authenticated/$slug/committee/tags'
      path: '/tags'
      fullPath: '/$slug/committee/tags'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeTagsRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/submissions': {
      id: '/_authenticated/$slug/committee/submissions'
      path: '/submissions'
      fullPath: '/$slug/committee/submissions'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeSubmissionsRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/settings': {
      id: '/_authenticated/$slug/committee/settings'
      path: '/settings'
      fullPath: '/$slug/committee/settings'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeSettingsRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/project-categories': {
      id: '/_authenticated/$slug/committee/project-categories'
      path: '/project-categories'
      fullPath: '/$slug/committee/project-categories'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/places': {
      id: '/_authenticated/$slug/committee/places'
      path: '/places'
      fullPath: '/$slug/committee/places'
      preLoaderRoute: typeof AuthenticatedSlugCommitteePlacesRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/organizations': {
      id: '/_authenticated/$slug/committee/organizations'
      path: '/organizations'
      fullPath: '/$slug/committee/organizations'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/members': {
      id: '/_authenticated/$slug/committee/members'
      path: '/members'
      fullPath: '/$slug/committee/members'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeMembersRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/export': {
      id: '/_authenticated/$slug/committee/export'
      path: '/export'
      fullPath: '/$slug/committee/export'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeExportRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/deadlines': {
      id: '/_authenticated/$slug/committee/deadlines'
      path: '/deadlines'
      fullPath: '/$slug/committee/deadlines'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeDeadlinesRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/admin/events_/$eventId/': {
      id: '/_authenticated/admin/events_/$eventId/'
      path: '/'
      fullPath: '/admin/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedAdminEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEventsEventIdRoute
    }
    '/_authenticated/$slug/orgs/$orgId/': {
      id: '/_authenticated/$slug/orgs/$orgId/'
      path: '/'
      fullPath: '/$slug/orgs/$orgId/'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedSlugOrgsOrgIdRoute
    }
    '/_authenticated/admin/events_/$eventId/users': {
      id: '/_authenticated/admin/events_/$eventId/users'
      path: '/users'
      fullPath: '/admin/events/$eventId/users'
      preLoaderRoute: typeof AuthenticatedAdminEventsEventIdUsersRouteImport
      parentRoute: typeof AuthenticatedAdminEventsEventIdRoute
    }
    '/_authenticated/$slug/orgs/$orgId/members': {
      id: '/_authenticated/$slug/orgs/$orgId/members'
      path: '/members'
      fullPath: '/$slug/orgs/$orgId/members'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedSlugOrgsOrgIdRoute
    }
    '/_authenticated/$slug/committee/tags/new': {
      id: '/_authenticated/$slug/committee/tags/new'
      path: '/new'
      fullPath: '/$slug/committee/tags/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeTagsNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeTagsRoute
    }
    '/_authenticated/$slug/committee/submissions_/$submissionId': {
      id: '/_authenticated/$slug/committee/submissions_/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/$slug/committee/submissions/$submissionId'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/project-categories/new': {
      id: '/_authenticated/$slug/committee/project-categories/new'
      path: '/new'
      fullPath: '/$slug/committee/project-categories/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesRoute
    }
    '/_authenticated/$slug/committee/places/new': {
      id: '/_authenticated/$slug/committee/places/new'
      path: '/new'
      fullPath: '/$slug/committee/places/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteePlacesNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteePlacesRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/$slug/committee/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/organizations/new': {
      id: '/_authenticated/$slug/committee/organizations/new'
      path: '/new'
      fullPath: '/$slug/committee/organizations/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsRoute
    }
    '/_authenticated/$slug/committee/deadlines/new': {
      id: '/_authenticated/$slug/committee/deadlines/new'
      path: '/new'
      fullPath: '/$slug/committee/deadlines/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeDeadlinesNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeDeadlinesRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/'
      path: '/'
      fullPath: '/$slug/committee/organizations/$orgId/'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRoute
    }
    '/_authenticated/$slug/orgs/$orgId/members/new': {
      id: '/_authenticated/$slug/orgs/$orgId/members/new'
      path: '/new'
      fullPath: '/$slug/orgs/$orgId/members/new'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdMembersNewRouteImport
      parentRoute: typeof AuthenticatedSlugOrgsOrgIdMembersRoute
    }
    '/_authenticated/$slug/committee/tags/$tagId/edit': {
      id: '/_authenticated/$slug/committee/tags/$tagId/edit'
      path: '/$tagId/edit'
      fullPath: '/$slug/committee/tags/$tagId/edit'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeTagsTagIdEditRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeTagsRoute
    }
    '/_authenticated/$slug/committee/project-categories/$categoryId/edit': {
      id: '/_authenticated/$slug/committee/project-categories/$categoryId/edit'
      path: '/$categoryId/edit'
      fullPath: '/$slug/committee/project-categories/$categoryId/edit'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesRoute
    }
    '/_authenticated/$slug/committee/places/$placeId/edit': {
      id: '/_authenticated/$slug/committee/places/$placeId/edit'
      path: '/$placeId/edit'
      fullPath: '/$slug/committee/places/$placeId/edit'
      preLoaderRoute: typeof AuthenticatedSlugCommitteePlacesPlaceIdEditRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteePlacesRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/projects': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/projects'
      path: '/projects'
      fullPath: '/$slug/committee/organizations/$orgId/projects'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/members': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/members'
      path: '/members'
      fullPath: '/$slug/committee/organizations/$orgId/members'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRoute
    }
    '/_authenticated/$slug/committee/deadlines/$deadlineId/edit': {
      id: '/_authenticated/$slug/committee/deadlines/$deadlineId/edit'
      path: '/$deadlineId/edit'
      fullPath: '/$slug/committee/deadlines/$deadlineId/edit'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeDeadlinesRoute
    }
    '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/': {
      id: '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/'
      path: '/orgs/$orgId/projects/$projectId'
      fullPath: '/$slug/orgs/$orgId/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions': {
      id: '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions'
      path: '/orgs/$orgId/projects/$projectId/submissions'
      fullPath: '/$slug/orgs/$orgId/projects/$projectId/submissions'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/edit': {
      id: '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/edit'
      path: '/orgs/$orgId/projects/$projectId/edit'
      fullPath: '/$slug/orgs/$orgId/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId_/projects/$projectId': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId_/projects/$projectId'
      path: '/organizations/$orgId/projects/$projectId'
      fullPath: '/$slug/committee/organizations/$orgId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/projects/new': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/projects/new'
      path: '/new'
      fullPath: '/$slug/committee/organizations/$orgId/projects/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/members/new': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/members/new'
      path: '/new'
      fullPath: '/$slug/committee/organizations/$orgId/members/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRoute
    }
    '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions_/$submissionId': {
      id: '/_authenticated/$slug/orgs/$orgId_/projects/$projectId/submissions_/$submissionId'
      path: '/orgs/$orgId/projects/$projectId/submissions/$submissionId'
      fullPath: '/$slug/orgs/$orgId/projects/$projectId/submissions/$submissionId'
      preLoaderRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
  }
}

interface AuthenticatedSlugCommitteeDeadlinesRouteChildren {
  AuthenticatedSlugCommitteeDeadlinesNewRoute: typeof AuthenticatedSlugCommitteeDeadlinesNewRoute
  AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute: typeof AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute
}

const AuthenticatedSlugCommitteeDeadlinesRouteChildren: AuthenticatedSlugCommitteeDeadlinesRouteChildren =
  {
    AuthenticatedSlugCommitteeDeadlinesNewRoute:
      AuthenticatedSlugCommitteeDeadlinesNewRoute,
    AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute:
      AuthenticatedSlugCommitteeDeadlinesDeadlineIdEditRoute,
  }

const AuthenticatedSlugCommitteeDeadlinesRouteWithChildren =
  AuthenticatedSlugCommitteeDeadlinesRoute._addFileChildren(
    AuthenticatedSlugCommitteeDeadlinesRouteChildren,
  )

interface AuthenticatedSlugCommitteeOrganizationsRouteChildren {
  AuthenticatedSlugCommitteeOrganizationsNewRoute: typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
}

const AuthenticatedSlugCommitteeOrganizationsRouteChildren: AuthenticatedSlugCommitteeOrganizationsRouteChildren =
  {
    AuthenticatedSlugCommitteeOrganizationsNewRoute:
      AuthenticatedSlugCommitteeOrganizationsNewRoute,
  }

const AuthenticatedSlugCommitteeOrganizationsRouteWithChildren =
  AuthenticatedSlugCommitteeOrganizationsRoute._addFileChildren(
    AuthenticatedSlugCommitteeOrganizationsRouteChildren,
  )

interface AuthenticatedSlugCommitteePlacesRouteChildren {
  AuthenticatedSlugCommitteePlacesNewRoute: typeof AuthenticatedSlugCommitteePlacesNewRoute
  AuthenticatedSlugCommitteePlacesPlaceIdEditRoute: typeof AuthenticatedSlugCommitteePlacesPlaceIdEditRoute
}

const AuthenticatedSlugCommitteePlacesRouteChildren: AuthenticatedSlugCommitteePlacesRouteChildren =
  {
    AuthenticatedSlugCommitteePlacesNewRoute:
      AuthenticatedSlugCommitteePlacesNewRoute,
    AuthenticatedSlugCommitteePlacesPlaceIdEditRoute:
      AuthenticatedSlugCommitteePlacesPlaceIdEditRoute,
  }

const AuthenticatedSlugCommitteePlacesRouteWithChildren =
  AuthenticatedSlugCommitteePlacesRoute._addFileChildren(
    AuthenticatedSlugCommitteePlacesRouteChildren,
  )

interface AuthenticatedSlugCommitteeProjectCategoriesRouteChildren {
  AuthenticatedSlugCommitteeProjectCategoriesNewRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesNewRoute
  AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute
}

const AuthenticatedSlugCommitteeProjectCategoriesRouteChildren: AuthenticatedSlugCommitteeProjectCategoriesRouteChildren =
  {
    AuthenticatedSlugCommitteeProjectCategoriesNewRoute:
      AuthenticatedSlugCommitteeProjectCategoriesNewRoute,
    AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute:
      AuthenticatedSlugCommitteeProjectCategoriesCategoryIdEditRoute,
  }

const AuthenticatedSlugCommitteeProjectCategoriesRouteWithChildren =
  AuthenticatedSlugCommitteeProjectCategoriesRoute._addFileChildren(
    AuthenticatedSlugCommitteeProjectCategoriesRouteChildren,
  )

interface AuthenticatedSlugCommitteeTagsRouteChildren {
  AuthenticatedSlugCommitteeTagsNewRoute: typeof AuthenticatedSlugCommitteeTagsNewRoute
  AuthenticatedSlugCommitteeTagsTagIdEditRoute: typeof AuthenticatedSlugCommitteeTagsTagIdEditRoute
}

const AuthenticatedSlugCommitteeTagsRouteChildren: AuthenticatedSlugCommitteeTagsRouteChildren =
  {
    AuthenticatedSlugCommitteeTagsNewRoute:
      AuthenticatedSlugCommitteeTagsNewRoute,
    AuthenticatedSlugCommitteeTagsTagIdEditRoute:
      AuthenticatedSlugCommitteeTagsTagIdEditRoute,
  }

const AuthenticatedSlugCommitteeTagsRouteWithChildren =
  AuthenticatedSlugCommitteeTagsRoute._addFileChildren(
    AuthenticatedSlugCommitteeTagsRouteChildren,
  )

interface AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteChildren {
  AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute
}

const AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteChildren: AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteChildren =
  {
    AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdMembersNewRoute,
  }

const AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteWithChildren =
  AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRoute._addFileChildren(
    AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteChildren,
  )

interface AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren {
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
}

const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren: AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren =
  {
    AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute,
  }

const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren =
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute._addFileChildren(
    AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren,
  )

interface AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren {
  AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteWithChildren
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
}

const AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren: AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren =
  {
    AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdMembersRouteWithChildren,
    AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren,
    AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute,
  }

const AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren =
  AuthenticatedSlugCommitteeOrganizationsOrgIdRoute._addFileChildren(
    AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren,
  )

interface AuthenticatedSlugCommitteeRouteChildren {
  AuthenticatedSlugCommitteeDeadlinesRoute: typeof AuthenticatedSlugCommitteeDeadlinesRouteWithChildren
  AuthenticatedSlugCommitteeExportRoute: typeof AuthenticatedSlugCommitteeExportRoute
  AuthenticatedSlugCommitteeMembersRoute: typeof AuthenticatedSlugCommitteeMembersRoute
  AuthenticatedSlugCommitteeOrganizationsRoute: typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  AuthenticatedSlugCommitteePlacesRoute: typeof AuthenticatedSlugCommitteePlacesRouteWithChildren
  AuthenticatedSlugCommitteeProjectCategoriesRoute: typeof AuthenticatedSlugCommitteeProjectCategoriesRouteWithChildren
  AuthenticatedSlugCommitteeSettingsRoute: typeof AuthenticatedSlugCommitteeSettingsRoute
  AuthenticatedSlugCommitteeSubmissionsRoute: typeof AuthenticatedSlugCommitteeSubmissionsRoute
  AuthenticatedSlugCommitteeTagsRoute: typeof AuthenticatedSlugCommitteeTagsRouteWithChildren
  AuthenticatedSlugCommitteeOrganizationsOrgIdRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren
  AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute: typeof AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute
}

const AuthenticatedSlugCommitteeRouteChildren: AuthenticatedSlugCommitteeRouteChildren =
  {
    AuthenticatedSlugCommitteeDeadlinesRoute:
      AuthenticatedSlugCommitteeDeadlinesRouteWithChildren,
    AuthenticatedSlugCommitteeExportRoute:
      AuthenticatedSlugCommitteeExportRoute,
    AuthenticatedSlugCommitteeMembersRoute:
      AuthenticatedSlugCommitteeMembersRoute,
    AuthenticatedSlugCommitteeOrganizationsRoute:
      AuthenticatedSlugCommitteeOrganizationsRouteWithChildren,
    AuthenticatedSlugCommitteePlacesRoute:
      AuthenticatedSlugCommitteePlacesRouteWithChildren,
    AuthenticatedSlugCommitteeProjectCategoriesRoute:
      AuthenticatedSlugCommitteeProjectCategoriesRouteWithChildren,
    AuthenticatedSlugCommitteeSettingsRoute:
      AuthenticatedSlugCommitteeSettingsRoute,
    AuthenticatedSlugCommitteeSubmissionsRoute:
      AuthenticatedSlugCommitteeSubmissionsRoute,
    AuthenticatedSlugCommitteeTagsRoute:
      AuthenticatedSlugCommitteeTagsRouteWithChildren,
    AuthenticatedSlugCommitteeOrganizationsOrgIdRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren,
    AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute:
      AuthenticatedSlugCommitteeSubmissionsSubmissionIdRoute,
    AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsProjectIdRoute,
  }

const AuthenticatedSlugCommitteeRouteWithChildren =
  AuthenticatedSlugCommitteeRoute._addFileChildren(
    AuthenticatedSlugCommitteeRouteChildren,
  )

interface AuthenticatedSlugOrgsOrgIdMembersRouteChildren {
  AuthenticatedSlugOrgsOrgIdMembersNewRoute: typeof AuthenticatedSlugOrgsOrgIdMembersNewRoute
}

const AuthenticatedSlugOrgsOrgIdMembersRouteChildren: AuthenticatedSlugOrgsOrgIdMembersRouteChildren =
  {
    AuthenticatedSlugOrgsOrgIdMembersNewRoute:
      AuthenticatedSlugOrgsOrgIdMembersNewRoute,
  }

const AuthenticatedSlugOrgsOrgIdMembersRouteWithChildren =
  AuthenticatedSlugOrgsOrgIdMembersRoute._addFileChildren(
    AuthenticatedSlugOrgsOrgIdMembersRouteChildren,
  )

interface AuthenticatedSlugOrgsOrgIdRouteChildren {
  AuthenticatedSlugOrgsOrgIdMembersRoute: typeof AuthenticatedSlugOrgsOrgIdMembersRouteWithChildren
  AuthenticatedSlugOrgsOrgIdIndexRoute: typeof AuthenticatedSlugOrgsOrgIdIndexRoute
}

const AuthenticatedSlugOrgsOrgIdRouteChildren: AuthenticatedSlugOrgsOrgIdRouteChildren =
  {
    AuthenticatedSlugOrgsOrgIdMembersRoute:
      AuthenticatedSlugOrgsOrgIdMembersRouteWithChildren,
    AuthenticatedSlugOrgsOrgIdIndexRoute: AuthenticatedSlugOrgsOrgIdIndexRoute,
  }

const AuthenticatedSlugOrgsOrgIdRouteWithChildren =
  AuthenticatedSlugOrgsOrgIdRoute._addFileChildren(
    AuthenticatedSlugOrgsOrgIdRouteChildren,
  )

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugCommitteeRoute: typeof AuthenticatedSlugCommitteeRouteWithChildren
  AuthenticatedSlugIndexRoute: typeof AuthenticatedSlugIndexRoute
  AuthenticatedSlugOrgsOrgIdRoute: typeof AuthenticatedSlugOrgsOrgIdRouteWithChildren
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute: typeof AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugCommitteeRoute: AuthenticatedSlugCommitteeRouteWithChildren,
  AuthenticatedSlugIndexRoute: AuthenticatedSlugIndexRoute,
  AuthenticatedSlugOrgsOrgIdRoute: AuthenticatedSlugOrgsOrgIdRouteWithChildren,
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute:
    AuthenticatedSlugOrgsOrgIdProjectsProjectIdEditRoute,
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute:
    AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsRoute,
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute:
    AuthenticatedSlugOrgsOrgIdProjectsProjectIdIndexRoute,
  AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute:
    AuthenticatedSlugOrgsOrgIdProjectsProjectIdSubmissionsSubmissionIdRoute,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedAdminApiKeysRouteChildren {
  AuthenticatedAdminApiKeysNewRoute: typeof AuthenticatedAdminApiKeysNewRoute
}

const AuthenticatedAdminApiKeysRouteChildren: AuthenticatedAdminApiKeysRouteChildren =
  {
    AuthenticatedAdminApiKeysNewRoute: AuthenticatedAdminApiKeysNewRoute,
  }

const AuthenticatedAdminApiKeysRouteWithChildren =
  AuthenticatedAdminApiKeysRoute._addFileChildren(
    AuthenticatedAdminApiKeysRouteChildren,
  )

interface AuthenticatedAdminEventsRouteChildren {
  AuthenticatedAdminEventsNewRoute: typeof AuthenticatedAdminEventsNewRoute
}

const AuthenticatedAdminEventsRouteChildren: AuthenticatedAdminEventsRouteChildren =
  {
    AuthenticatedAdminEventsNewRoute: AuthenticatedAdminEventsNewRoute,
  }

const AuthenticatedAdminEventsRouteWithChildren =
  AuthenticatedAdminEventsRoute._addFileChildren(
    AuthenticatedAdminEventsRouteChildren,
  )

interface AuthenticatedAdminEventsEventIdRouteChildren {
  AuthenticatedAdminEventsEventIdUsersRoute: typeof AuthenticatedAdminEventsEventIdUsersRoute
  AuthenticatedAdminEventsEventIdIndexRoute: typeof AuthenticatedAdminEventsEventIdIndexRoute
}

const AuthenticatedAdminEventsEventIdRouteChildren: AuthenticatedAdminEventsEventIdRouteChildren =
  {
    AuthenticatedAdminEventsEventIdUsersRoute:
      AuthenticatedAdminEventsEventIdUsersRoute,
    AuthenticatedAdminEventsEventIdIndexRoute:
      AuthenticatedAdminEventsEventIdIndexRoute,
  }

const AuthenticatedAdminEventsEventIdRouteWithChildren =
  AuthenticatedAdminEventsEventIdRoute._addFileChildren(
    AuthenticatedAdminEventsEventIdRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRouteWithChildren
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEventsEventIdRoute: typeof AuthenticatedAdminEventsEventIdRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRouteWithChildren,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEventsEventIdRoute:
    AuthenticatedAdminEventsEventIdRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
