/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedSlugRouteImport } from './routes/_authenticated/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events_.$eventId'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events.new'
import { Route as AdminEventsEventIdIndexRouteImport } from './routes/admin/events_.$eventId.index'
import { Route as AuthenticatedSlugCommitteeIndexRouteImport } from './routes/_authenticated/$slug/committee/index'
import { Route as AdminEventsEventIdUsersRouteImport } from './routes/admin/events_.$eventId.users'
import { Route as AuthenticatedSlugCommitteeTagsRouteImport } from './routes/_authenticated/$slug/committee/tags'
import { Route as AuthenticatedSlugCommitteePlacesRouteImport } from './routes/_authenticated/$slug/committee/places'
import { Route as AuthenticatedSlugCommitteeOrganizationsRouteImport } from './routes/_authenticated/$slug/committee/organizations'
import { Route as AuthenticatedSlugCommitteeDeadlinesRouteImport } from './routes/_authenticated/$slug/committee/deadlines'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId'
import { Route as AuthenticatedSlugCommitteeOrganizationsNewRouteImport } from './routes/_authenticated/$slug/committee/organizations.new'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.index'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.projects'
import { Route as AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRouteImport } from './routes/_authenticated/$slug/committee/organizations_/$orgId.projects.new'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSlugRoute = AuthenticatedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events_/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminEventsEventIdIndexRoute = AdminEventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventsEventIdRoute,
} as any)
const AuthenticatedSlugCommitteeIndexRoute =
  AuthenticatedSlugCommitteeIndexRouteImport.update({
    id: '/committee/',
    path: '/committee/',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AdminEventsEventIdUsersRoute = AdminEventsEventIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminEventsEventIdRoute,
} as any)
const AuthenticatedSlugCommitteeTagsRoute =
  AuthenticatedSlugCommitteeTagsRouteImport.update({
    id: '/committee/tags',
    path: '/committee/tags',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCommitteePlacesRoute =
  AuthenticatedSlugCommitteePlacesRouteImport.update({
    id: '/committee/places',
    path: '/committee/places',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsRoute =
  AuthenticatedSlugCommitteeOrganizationsRouteImport.update({
    id: '/committee/organizations',
    path: '/committee/organizations',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCommitteeDeadlinesRoute =
  AuthenticatedSlugCommitteeDeadlinesRouteImport.update({
    id: '/committee/deadlines',
    path: '/committee/deadlines',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdRouteImport.update({
    id: '/committee/organizations_/$orgId',
    path: '/committee/organizations/$orgId',
    getParentRoute: () => AuthenticatedSlugRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsNewRoute =
  AuthenticatedSlugCommitteeOrganizationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSlugCommitteeOrganizationsRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSlugCommitteeOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedSlugCommitteeOrganizationsOrgIdRoute,
  } as any)
const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute =
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () =>
      AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/test': typeof AuthenticatedTestRoute
  '/login': typeof PublicLoginRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/committee/deadlines': typeof AuthenticatedSlugCommitteeDeadlinesRoute
  '/$slug/committee/organizations': typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  '/$slug/committee/places': typeof AuthenticatedSlugCommitteePlacesRoute
  '/$slug/committee/tags': typeof AuthenticatedSlugCommitteeTagsRoute
  '/admin/events/$eventId/users': typeof AdminEventsEventIdUsersRoute
  '/$slug/committee/': typeof AuthenticatedSlugCommitteeIndexRoute
  '/admin/events/$eventId/': typeof AdminEventsEventIdIndexRoute
  '/$slug/committee/organizations/new': typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
  '/$slug/committee/organizations/$orgId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren
  '/$slug/committee/organizations/$orgId/projects': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  '/$slug/committee/organizations/$orgId/': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
  '/$slug/committee/organizations/$orgId/projects/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/test': typeof AuthenticatedTestRoute
  '/login': typeof PublicLoginRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$slug/committee/deadlines': typeof AuthenticatedSlugCommitteeDeadlinesRoute
  '/$slug/committee/organizations': typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  '/$slug/committee/places': typeof AuthenticatedSlugCommitteePlacesRoute
  '/$slug/committee/tags': typeof AuthenticatedSlugCommitteeTagsRoute
  '/admin/events/$eventId/users': typeof AdminEventsEventIdUsersRoute
  '/$slug/committee': typeof AuthenticatedSlugCommitteeIndexRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdIndexRoute
  '/$slug/committee/organizations/new': typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
  '/$slug/committee/organizations/$orgId/projects': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  '/$slug/committee/organizations/$orgId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
  '/$slug/committee/organizations/$orgId/projects/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_authenticated/$slug': typeof AuthenticatedSlugRouteWithChildren
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/_public/login': typeof PublicLoginRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events_/$eventId': typeof AdminEventsEventIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/$slug/committee/deadlines': typeof AuthenticatedSlugCommitteeDeadlinesRoute
  '/_authenticated/$slug/committee/organizations': typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  '/_authenticated/$slug/committee/places': typeof AuthenticatedSlugCommitteePlacesRoute
  '/_authenticated/$slug/committee/tags': typeof AuthenticatedSlugCommitteeTagsRoute
  '/admin/events_/$eventId/users': typeof AdminEventsEventIdUsersRoute
  '/_authenticated/$slug/committee/': typeof AuthenticatedSlugCommitteeIndexRoute
  '/admin/events_/$eventId/': typeof AdminEventsEventIdIndexRoute
  '/_authenticated/$slug/committee/organizations/new': typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
  '/_authenticated/$slug/committee/organizations_/$orgId': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren
  '/_authenticated/$slug/committee/organizations_/$orgId/projects': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  '/_authenticated/$slug/committee/organizations_/$orgId/': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
  '/_authenticated/$slug/committee/organizations_/$orgId/projects/new': typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/$slug'
    | '/test'
    | '/login'
    | '/admin/events'
    | '/admin/users'
    | '/admin/events/new'
    | '/admin/events/$eventId'
    | '/api/auth/$'
    | '/$slug/committee/deadlines'
    | '/$slug/committee/organizations'
    | '/$slug/committee/places'
    | '/$slug/committee/tags'
    | '/admin/events/$eventId/users'
    | '/$slug/committee/'
    | '/admin/events/$eventId/'
    | '/$slug/committee/organizations/new'
    | '/$slug/committee/organizations/$orgId'
    | '/$slug/committee/organizations/$orgId/projects'
    | '/$slug/committee/organizations/$orgId/'
    | '/$slug/committee/organizations/$orgId/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/$slug'
    | '/test'
    | '/login'
    | '/admin/events'
    | '/admin/users'
    | '/admin/events/new'
    | '/api/auth/$'
    | '/$slug/committee/deadlines'
    | '/$slug/committee/organizations'
    | '/$slug/committee/places'
    | '/$slug/committee/tags'
    | '/admin/events/$eventId/users'
    | '/$slug/committee'
    | '/admin/events/$eventId'
    | '/$slug/committee/organizations/new'
    | '/$slug/committee/organizations/$orgId/projects'
    | '/$slug/committee/organizations/$orgId'
    | '/$slug/committee/organizations/$orgId/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/admin'
    | '/_authenticated/$slug'
    | '/_authenticated/test'
    | '/_public/login'
    | '/admin/events'
    | '/admin/users'
    | '/admin/events/new'
    | '/admin/events_/$eventId'
    | '/api/auth/$'
    | '/_authenticated/$slug/committee/deadlines'
    | '/_authenticated/$slug/committee/organizations'
    | '/_authenticated/$slug/committee/places'
    | '/_authenticated/$slug/committee/tags'
    | '/admin/events_/$eventId/users'
    | '/_authenticated/$slug/committee/'
    | '/admin/events_/$eventId/'
    | '/_authenticated/$slug/committee/organizations/new'
    | '/_authenticated/$slug/committee/organizations_/$orgId'
    | '/_authenticated/$slug/committee/organizations_/$orgId/projects'
    | '/_authenticated/$slug/committee/organizations_/$orgId/'
    | '/_authenticated/$slug/committee/organizations_/$orgId/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$slug': {
      id: '/_authenticated/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof AuthenticatedSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events_/$eventId': {
      id: '/admin/events_/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/events_/$eventId/': {
      id: '/admin/events_/$eventId/'
      path: '/'
      fullPath: '/admin/events/$eventId/'
      preLoaderRoute: typeof AdminEventsEventIdIndexRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/_authenticated/$slug/committee/': {
      id: '/_authenticated/$slug/committee/'
      path: '/committee'
      fullPath: '/$slug/committee/'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeIndexRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/admin/events_/$eventId/users': {
      id: '/admin/events_/$eventId/users'
      path: '/users'
      fullPath: '/admin/events/$eventId/users'
      preLoaderRoute: typeof AdminEventsEventIdUsersRouteImport
      parentRoute: typeof AdminEventsEventIdRoute
    }
    '/_authenticated/$slug/committee/tags': {
      id: '/_authenticated/$slug/committee/tags'
      path: '/committee/tags'
      fullPath: '/$slug/committee/tags'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeTagsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/committee/places': {
      id: '/_authenticated/$slug/committee/places'
      path: '/committee/places'
      fullPath: '/$slug/committee/places'
      preLoaderRoute: typeof AuthenticatedSlugCommitteePlacesRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/committee/organizations': {
      id: '/_authenticated/$slug/committee/organizations'
      path: '/committee/organizations'
      fullPath: '/$slug/committee/organizations'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/committee/deadlines': {
      id: '/_authenticated/$slug/committee/deadlines'
      path: '/committee/deadlines'
      fullPath: '/$slug/committee/deadlines'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeDeadlinesRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId'
      path: '/committee/organizations/$orgId'
      fullPath: '/$slug/committee/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedSlugRoute
    }
    '/_authenticated/$slug/committee/organizations/new': {
      id: '/_authenticated/$slug/committee/organizations/new'
      path: '/new'
      fullPath: '/$slug/committee/organizations/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/'
      path: '/'
      fullPath: '/$slug/committee/organizations/$orgId/'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/projects': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/projects'
      path: '/projects'
      fullPath: '/$slug/committee/organizations/$orgId/projects'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRoute
    }
    '/_authenticated/$slug/committee/organizations_/$orgId/projects/new': {
      id: '/_authenticated/$slug/committee/organizations_/$orgId/projects/new'
      path: '/new'
      fullPath: '/$slug/committee/organizations/$orgId/projects/new'
      preLoaderRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRouteImport
      parentRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute
    }
  }
}

interface AuthenticatedSlugCommitteeOrganizationsRouteChildren {
  AuthenticatedSlugCommitteeOrganizationsNewRoute: typeof AuthenticatedSlugCommitteeOrganizationsNewRoute
}

const AuthenticatedSlugCommitteeOrganizationsRouteChildren: AuthenticatedSlugCommitteeOrganizationsRouteChildren =
  {
    AuthenticatedSlugCommitteeOrganizationsNewRoute:
      AuthenticatedSlugCommitteeOrganizationsNewRoute,
  }

const AuthenticatedSlugCommitteeOrganizationsRouteWithChildren =
  AuthenticatedSlugCommitteeOrganizationsRoute._addFileChildren(
    AuthenticatedSlugCommitteeOrganizationsRouteChildren,
  )

interface AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren {
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute
}

const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren: AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren =
  {
    AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsNewRoute,
  }

const AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren =
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute._addFileChildren(
    AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteChildren,
  )

interface AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren {
  AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren
  AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute
}

const AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren: AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren =
  {
    AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdProjectsRouteWithChildren,
    AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute:
      AuthenticatedSlugCommitteeOrganizationsOrgIdIndexRoute,
  }

const AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren =
  AuthenticatedSlugCommitteeOrganizationsOrgIdRoute._addFileChildren(
    AuthenticatedSlugCommitteeOrganizationsOrgIdRouteChildren,
  )

interface AuthenticatedSlugRouteChildren {
  AuthenticatedSlugCommitteeDeadlinesRoute: typeof AuthenticatedSlugCommitteeDeadlinesRoute
  AuthenticatedSlugCommitteeOrganizationsRoute: typeof AuthenticatedSlugCommitteeOrganizationsRouteWithChildren
  AuthenticatedSlugCommitteePlacesRoute: typeof AuthenticatedSlugCommitteePlacesRoute
  AuthenticatedSlugCommitteeTagsRoute: typeof AuthenticatedSlugCommitteeTagsRoute
  AuthenticatedSlugCommitteeIndexRoute: typeof AuthenticatedSlugCommitteeIndexRoute
  AuthenticatedSlugCommitteeOrganizationsOrgIdRoute: typeof AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren
}

const AuthenticatedSlugRouteChildren: AuthenticatedSlugRouteChildren = {
  AuthenticatedSlugCommitteeDeadlinesRoute:
    AuthenticatedSlugCommitteeDeadlinesRoute,
  AuthenticatedSlugCommitteeOrganizationsRoute:
    AuthenticatedSlugCommitteeOrganizationsRouteWithChildren,
  AuthenticatedSlugCommitteePlacesRoute: AuthenticatedSlugCommitteePlacesRoute,
  AuthenticatedSlugCommitteeTagsRoute: AuthenticatedSlugCommitteeTagsRoute,
  AuthenticatedSlugCommitteeIndexRoute: AuthenticatedSlugCommitteeIndexRoute,
  AuthenticatedSlugCommitteeOrganizationsOrgIdRoute:
    AuthenticatedSlugCommitteeOrganizationsOrgIdRouteWithChildren,
}

const AuthenticatedSlugRouteWithChildren =
  AuthenticatedSlugRoute._addFileChildren(AuthenticatedSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSlugRoute: typeof AuthenticatedSlugRouteWithChildren
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSlugRoute: AuthenticatedSlugRouteWithChildren,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminEventsRouteChildren {
  AdminEventsNewRoute: typeof AdminEventsNewRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsNewRoute: AdminEventsNewRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminEventsEventIdRouteChildren {
  AdminEventsEventIdUsersRoute: typeof AdminEventsEventIdUsersRoute
  AdminEventsEventIdIndexRoute: typeof AdminEventsEventIdIndexRoute
}

const AdminEventsEventIdRouteChildren: AdminEventsEventIdRouteChildren = {
  AdminEventsEventIdUsersRoute: AdminEventsEventIdUsersRoute,
  AdminEventsEventIdIndexRoute: AdminEventsEventIdIndexRoute,
}

const AdminEventsEventIdRouteWithChildren =
  AdminEventsEventIdRoute._addFileChildren(AdminEventsEventIdRouteChildren)

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
