name: Check

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: Lint, Format & Test
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@e34774bccb4e7d7f2e23514ca980177a71425e43 # v1
        with:
          node-version: lts/*
          cache: true

      - name: Format check
        run: vp fmt --check

      - name: Build packages
        run: vp run -F '@archive/*' build

      - name: Lint
        run: vp run -r lint

      - name: Test
        run: vp run -r test
